# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lot.ui'
#
# Created: Wed May 20 19:59:18 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_lot(object):
    def setupUi(self, lot):
        lot.setObjectName("lot")
        lot.resize(746, 394)
        self.buttonBox = QtGui.QDialogButtonBox(lot)
        self.buttonBox.setGeometry(QtCore.QRect(0, 350, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tableImage = QtGui.QTableWidget(lot)
        self.tableImage.setGeometry(QtCore.QRect(10, 30, 321, 311))
        self.tableImage.setObjectName("tableImage")
        self.tableImage.setColumnCount(3)
        self.tableImage.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableImage.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableImage.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableImage.setHorizontalHeaderItem(2, item)
        self.groupBox_3 = QtGui.QGroupBox(lot)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 90, 396, 121))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setMargin(1)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.time = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setMinimumSize(QtCore.QSize(0, 26))
        self.time.setMinimum(1)
        self.time.setObjectName("time")
        self.gridLayout_3.addWidget(self.time, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bgfile = QtGui.QLineEdit(self.groupBox_3)
        self.bgfile.setMinimumSize(QtCore.QSize(0, 26))
        self.bgfile.setObjectName("bgfile")
        self.horizontalLayout_4.addWidget(self.bgfile)
        self.bgfilea = QtGui.QToolButton(self.groupBox_3)
        self.bgfilea.setObjectName("bgfilea")
        self.horizontalLayout_4.addWidget(self.bgfilea)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bgcolor = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgcolor.sizePolicy().hasHeightForWidth())
        self.bgcolor.setSizePolicy(sizePolicy)
        self.bgcolor.setMinimumSize(QtCore.QSize(0, 26))
        self.bgcolor.setObjectName("bgcolor")
        self.horizontalLayout_3.addWidget(self.bgcolor)
        self.bgcolora = QtGui.QToolButton(self.groupBox_3)
        self.bgcolora.setObjectName("bgcolora")
        self.horizontalLayout_3.addWidget(self.bgcolora)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(lot)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 220, 396, 121))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.speedt = QtGui.QComboBox(self.groupBox_4)
        self.speedt.setMinimumSize(QtCore.QSize(0, 26))
        self.speedt.setObjectName("speedt")
        self.speedt.addItem(QtCore.QString())
        self.speedt.addItem(QtCore.QString())
        self.speedt.addItem(QtCore.QString())
        self.speedt.addItem(QtCore.QString())
        self.speedt.addItem(QtCore.QString())
        self.speedt.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.speedt, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.typet = QtGui.QComboBox(self.groupBox_4)
        self.typet.setMinimumSize(QtCore.QSize(0, 26))
        self.typet.setObjectName("typet")
        self.gridLayout_2.addWidget(self.typet, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.transiopt = QtGui.QComboBox(self.groupBox_4)
        self.transiopt.setMinimumSize(QtCore.QSize(0, 26))
        self.transiopt.setObjectName("transiopt")
        self.gridLayout_2.addWidget(self.transiopt, 2, 1, 1, 1)
        self.label = QtGui.QLabel(lot)
        self.label.setGeometry(QtCore.QRect(10, -2, 321, 31))
        self.label.setObjectName("label")
        self.groupBox = QtGui.QGroupBox(lot)
        self.groupBox.setGeometry(QtCore.QRect(340, 30, 391, 51))
        self.groupBox.setObjectName("groupBox")
        self.fromc = QtGui.QSpinBox(self.groupBox)
        self.fromc.setGeometry(QtCore.QRect(100, 20, 81, 25))
        self.fromc.setMinimum(1)
        self.fromc.setObjectName("fromc")
        self.toc = QtGui.QSpinBox(self.groupBox)
        self.toc.setGeometry(QtCore.QRect(303, 20, 81, 25))
        self.toc.setMinimum(1)
        self.toc.setObjectName("toc")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 81, 19))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(220, 20, 81, 19))
        self.label_8.setObjectName("label_8")
        self.groupBox_2 = QtGui.QGroupBox(lot)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 340, 401, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.removeLine = QtGui.QToolButton(self.groupBox_2)
        self.removeLine.setGeometry(QtCore.QRect(360, 20, 30, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icones/pencil_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeLine.setIcon(icon)
        self.removeLine.setObjectName("removeLine")
        self.updateLine = QtGui.QToolButton(self.groupBox_2)
        self.updateLine.setGeometry(QtCore.QRect(280, 20, 30, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icones/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateLine.setIcon(icon1)
        self.updateLine.setObjectName("updateLine")
        self.empty = QtGui.QToolButton(self.groupBox_2)
        self.empty.setGeometry(QtCore.QRect(320, 20, 30, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icones/bin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.empty.setIcon(icon2)
        self.empty.setObjectName("empty")
        self.validLine = QtGui.QToolButton(self.groupBox_2)
        self.validLine.setGeometry(QtCore.QRect(240, 20, 30, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icones/pencil_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.validLine.setIcon(icon3)
        self.validLine.setObjectName("validLine")

        self.retranslateUi(lot)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), lot.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), lot.reject)
        QtCore.QMetaObject.connectSlotsByName(lot)

    def retranslateUi(self, lot):
        lot.setWindowTitle(QtGui.QApplication.translate("lot", "Option by lot", None, QtGui.QApplication.UnicodeUTF8))
        self.tableImage.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("lot", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.tableImage.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("lot", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.tableImage.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("lot", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("lot", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("lot", "Time display :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("lot", "Background file :", None, QtGui.QApplication.UnicodeUTF8))
        self.bgfilea.setToolTip(QtGui.QApplication.translate("lot", "Add background file", None, QtGui.QApplication.UnicodeUTF8))
        self.bgfilea.setText(QtGui.QApplication.translate("lot", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("lot", "Background color :", None, QtGui.QApplication.UnicodeUTF8))
        self.bgcolora.setToolTip(QtGui.QApplication.translate("lot", "Add background color", None, QtGui.QApplication.UnicodeUTF8))
        self.bgcolora.setText(QtGui.QApplication.translate("lot", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("lot", "Transition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("lot", "Transition speed :", None, QtGui.QApplication.UnicodeUTF8))
        self.speedt.setItemText(0, QtGui.QApplication.translate("lot", "Very slow", None, QtGui.QApplication.UnicodeUTF8))
        self.speedt.setItemText(1, QtGui.QApplication.translate("lot", "Slow", None, QtGui.QApplication.UnicodeUTF8))
        self.speedt.setItemText(2, QtGui.QApplication.translate("lot", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.speedt.setItemText(3, QtGui.QApplication.translate("lot", "Medium+", None, QtGui.QApplication.UnicodeUTF8))
        self.speedt.setItemText(4, QtGui.QApplication.translate("lot", "Fast", None, QtGui.QApplication.UnicodeUTF8))
        self.speedt.setItemText(5, QtGui.QApplication.translate("lot", "Very fast", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("lot", "Transition type :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("lot", "Transition option :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("lot", "List image to configure", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("lot", "Define range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("lot", "From :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("lot", "To :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("lot", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.removeLine.setToolTip(QtGui.QApplication.translate("lot", "Delete selected line", None, QtGui.QApplication.UnicodeUTF8))
        self.removeLine.setText(QtGui.QApplication.translate("lot", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.updateLine.setToolTip(QtGui.QApplication.translate("lot", "Update selected line", None, QtGui.QApplication.UnicodeUTF8))
        self.updateLine.setText(QtGui.QApplication.translate("lot", "Update selected line", None, QtGui.QApplication.UnicodeUTF8))
        self.empty.setToolTip(QtGui.QApplication.translate("lot", "Empty table", None, QtGui.QApplication.UnicodeUTF8))
        self.empty.setText(QtGui.QApplication.translate("lot", "Empty table", None, QtGui.QApplication.UnicodeUTF8))
        self.validLine.setToolTip(QtGui.QApplication.translate("lot", "Add new line", None, QtGui.QApplication.UnicodeUTF8))
        self.validLine.setText(QtGui.QApplication.translate("lot", "Add new line", None, QtGui.QApplication.UnicodeUTF8))

